-- 1) این فایل را در Supabase > SQL Editor اجرا کن.
-- 2) بعد در Authentication > Users یک کاربر ادمین بساز.
-- 3) کلید secret/service_role را هرگز در سایت قرار نده.

create table if not exists public.survey_responses (
  id bigint generated by default as identity primary key,
  survey_id text not null default 'visual-taste-v1',
  created_at timestamptz not null default now(),
  device text not null default 'unknown',
  device_details jsonb not null default '{}'::jsonb,
  answers jsonb not null,
  user_agent text,
  language text,
  timezone text,
  viewport_width integer,
  viewport_height integer,
  screen_width integer,
  screen_height integer,
  referrer text
);

alter table public.survey_responses enable row level security;

drop policy if exists "public can submit survey" on public.survey_responses;
create policy "public can submit survey"
on public.survey_responses
for insert
to anon, authenticated
with check (survey_id = 'visual-taste-v1');

drop policy if exists "admins can read survey" on public.survey_responses;
create policy "admins can read survey"
on public.survey_responses
for select
to authenticated
using (true);

drop policy if exists "admins can delete survey" on public.survey_responses;
create policy "admins can delete survey"
on public.survey_responses
for delete
to authenticated
using (true);

grant insert on public.survey_responses to anon, authenticated;
grant select, delete on public.survey_responses to authenticated;
grant usage, select on sequence public.survey_responses_id_seq to anon, authenticated;
